env:
  es2021: true
  node: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - airbnb-base
  - 'plugin:prettier/recommended'
  - 'plugin:import/errors'
  - 'plugin:import/warnings'
  - 'plugin:import/typescript'
  - next/core-web-vitals
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - '@typescript-eslint'
  - prettier
  - import
rules:
  prettier/prettier: error
  import/extensions: 'off'
  import/no-unresolved: error
  no-console: 'off'
  no-unused-vars:
    - 'off'
    - args: all
      argsIgnorePattern: ^_
  no-shadow: 'off'
  '@typescript-eslint/no-shadow':
    - error
  '@typescript-eslint/no-unused-vars':
    - 'off'
    - args: all
      argsIgnorePattern: ^_
  import/order:
    - error
    - newlines-between: never
      groups:
        - - builtin
          - external
        - - internal
          - parent
          - sibling
          - index
settings:
  import/parsers:
    '@typescript-eslint/parser':
      - .ts
  import/resolver:
    typescript:
      alwaysTryTypes: true
      project: ./tsconfig.json
